### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by KristjanESPERANTO** [bugsounet/MMM-Saint#4]
A screenshot would be nice :slightly_smiling_face:

**Comment by bugsounet** [comment]
this is my lazy mode that ! ;) ;)

**Comment by bugsounet** [comment]
done ;)

**Comment by KristjanESPERANTO** [comment]
Nice. Thanks! 🙂

**Comment by bugsounet** [comment]
Humm... On Germany, it's the same saint name?

**Comment by KristjanESPERANTO** [comment]
No, Germans use often a bit different names.

Examples:

- Ste Thérèse -> Therese von Lisieux
- St Martin -> Martin von Tours
- Ste Jeanne d'Arc -> Johanna von Orleans

I had to research this because I'm not familiar with names of christian saints.
